### PR TITLE
fix missing ClientPermissions registration

### PR DESCRIPTION
**Pull request by zhu-rengong**

### CODE REVIEW

**Comment by evilfactory** [comment]
This prevents you from doing bit wise operations on the enum flag, any way to solve this?

**Comment by evilfactory** [comment]
Possible solution:
Don't register ClientPermissions and assign the global ClientPermissions a table with the enum values, like this:

```lua
{
	None = 0x0,
	ManageRound = 0x1,
	Kick = 0x2,
	Ban = 0x4,
	Unban = 0x8,
	SelectSub = 0x10,
	SelectMode = 0x20,
	ManageCampaign = 0x40,
	ConsoleCommands = 0x80,
	ServerLog = 0x100,
	ManageSettings = 0x200,
	ManagePermissions = 0x400,
	KarmaImmunity = 0x800,
	All = 0xFFF
}
```

**Comment by zhu-rengong** [comment]
look:https://github.com/moonsharp-devs/moonsharp/blob/f19fbffeda5f36cba419df2170a812acc34cd13e/src/MoonSharp.Interpreter/Interop/StandardDescriptors/StandardEnumUserDataDescriptor.cs

It provides a way to perform such operations

```
...
				AddEnumMethod("flagsAnd", DynValue.NewCallback(Callback_And));
				AddEnumMethod("flagsOr", DynValue.NewCallback(Callback_Or));
				AddEnumMethod("flagsXor", DynValue.NewCallback(Callback_Xor));
				AddEnumMethod("flagsNot", DynValue.NewCallback(Callback_BwNot));
				AddEnumMethod("hasAll", DynValue.NewCallback(Callback_HasAll));
				AddEnumMethod("hasAny", DynValue.NewCallback(Callback_HasAny));
...
```

**Comment by evilfactory** [comment]
Some Lua mods still use the bit32.xor equivalent for it, so i'm not sure :/

**Comment by zhu-rengong** [comment]
Maybe Moonsharp does not overload the +-*/ operation for the Enum type on the lua side, so it needs to be implemented through some methods. it's the reason why there seems to be no problem with bit32, but if we use ClientPermission, it is very readable:
```lua
             ClientPermissions.__hasAll(client.Permissions, ClientPermissions.ManagePermissions)
             ClientPermissions.__flagsAnd(client.Permissions,
                 ClientPermissions.ManageRound ..
                 ClientPermissions.ManageCampaign ..
                 ClientPermissions.ManageSettings)
```

**Comment by evilfactory** [comment]
Maybe i can add the +-*/ operators via reflection, it's pretty late now, so i'm gonna just take a look tomorrow.

**Comment by zhu-rengong** [comment]
Good night, sweet dreams :>

**Comment by evilfactory** [comment]
I wasn't able to add the operations via reflection :/, i'm not sure whats the best solution for this, the first one i suggested seems the best one

**Comment by zhu-rengong** [comment]
Thank you, maybe one day, this problem will be solved.

**Pull request closed without merging**
